version: 2.1

jobs:
  Build_and_push_docker_image:
    docker:
      - image: cimg/node:23.10.0 
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  
      - run:
          name: Log in to DockerHub
          command: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t ${DOCKER_USERNAME}/portfolio .
      - run:
          name: Push Docker image to DockerHub
          command: docker push ${DOCKER_USERNAME}/portfolio

workflows:
  version: 2
  build_workflow:
    jobs:
      - Build_and_push_docker_image
